apiVersion: v1
kind: PersistentVolume
metadata:
  name: pagina-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /proyecto-cloud/static-website

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pagina-pvc
  namespace: static-website
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pagina-pv
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
