apiVersion: v1
kind: PersistentVolume
metadata:
  name: pagina-pv
  namespace: static-website
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/static-website
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pagina-pvc
  namespace: static-website
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
