apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagina-web
  namespace: static-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagina-web
  template:
    metadata:
      labels:
        app: pagina-web
    spec:
      containers:
      - name: nginx
        image: pagina-web-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
